TrajectoryPlannerROS:

  holonomic_robot: true
  meter_scoring: true
# =================UDACITY_BOT SETTINGS=======================
#  Uncomment the below settings when using the Udacity bot
#  pdist_scale: 1.2
#  max_vel_x: 2.0

# =================CUSTOM R2D2 BOT SETTINGS===================
# Uncomment the below settinsg when using the R2D2 bot
  pdist_scale: 0.75
  max_vel_x: 0.4
  max_vel_y: 0.4

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.15

  acc_lim_x: 0.5
  acc_lim_y: 0.5       
